midterm-s16.pdf: midterm-s16.tex
	pdflatex midterm-s16.tex
	pdflatex midterm-s16.tex
	pdflatex midterm-s16.tex

clean:
	rm -f midterm-s16.pdf *.aux *.blg *.bbl *.log *.tmp *.xref *.idv *.4og *.4ct *.lg *.4tc *~ *.out

mac: midterm-s16.pdf
	open -a preview.app midterm-s16.pdf
