#!/bin/csh
# 
# To execute this script, see ~cos126/assignments/hello/run-script



# echo "For more information on how to read this grade report, see the grade report guide:\nhttp://www.princeton.edu/~pmittal/teaching/ele432-spring15/gradeReport.html\n"

echo "Please report any apparent bugs in this Dropbox grading script on Piazza \n"

unalias *

limit cpu 100 seconds
limit core 0


set RELATIVE_PATH    = "`dirname $0`" #relative
set RUNSCRIPT_PATH   = "`( cd $RELATIVE_PATH && pwd)`" #absolutized and normalized
set GRADEROOT        = `dirname $RUNSCRIPT_PATH`
source $GRADEROOT/bin/setEnvironmentVariables
setenv IS_DROPBOX     1

# test data
set ASSIGNMENT_NAME  = "HW1"
setenv REQUIRED        "PRGen StreamCipher AuthEncryptor AuthDecryptor"
setenv EXTRA_CREDIT    ""
setenv FILES_TO_COPY   "*.txt"

if (! -d $WORKSPACE) then
    mkdir        $OUTPUT $WORKSPACE
    chmod 2770   $OUTPUT $WORKSPACE
endif

# do for each name in current directory
foreach name ($argv)

    /bin/rm -rf $WORKSPACE/$name  >>& /dev/null
    /bin/rm -rf $OUTPUT/$name  >>& /dev/null

    echo -n $name
    echo -n ": "
	
    # skip if directory doesn't exist
    set files  = `ls $name/*  |& grep -v "No such file or directory" |& grep -v "No match"`
    if ("$files" == "") then
        echo "no files submitted"
        continue
    endif

    touch $OUTPUT/$name
    $SCRIPTS/listfiles.scr  $name

    $SCRIPTS/compile.scr    $name
    $SCRIPTS/checkstyle.scr $name
    $SCRIPTS/findbugs.scr   $name
    $SCRIPTS/api.scr        $name

    $SCRIPTS/recompileGrader.scr $name        
    $SCRIPTS/execute.scr    $name PRGen
    
    #setenv PRINT_TEXT "executing StreamCipher with reference PRGen"
    #setenv ECHO_TEXT ""
    $SCRIPTS/execute.scr    $name StreamCipher

    #setenv PRINT_TEXT "executing AuthEncryptor and AuthDecryptor with reference PRGen and reference StreamCipher"
    #setenv ECHO_TEXT ""

    $SCRIPTS/execute.scr    $name AuthEncryptor AuthDecryptor    
    unsetenv PRINT_TEXT
    unsetenv ECHO_TEXT
    $SCRIPTS/postProcess.scr $name $REQUIRED  

    /bin/rm -rf $WORKSPACE/$name  >>& /dev/null

    echo "done.\n"

end
